#!/usr/bin/env node
import { writeFile } from 'fs/promises'
import { join } from 'path'
import { exists } from './lib/exists.js'

const pkgPath = join(process.cwd(), 'package.json')

if (!(await exists(pkgPath))) {
  await writeFile(pkgPath, JSON.stringify({
    version: '1.0.0',
    description: 'Generated by cloudflare-manager, for the enmap to work!'
  }, null, 2), {
    encoding: 'utf-8'
  })
}

await import('./app.js')